### PR TITLE
scan: Add version to result and save absolute path of root

### LINKED ISSUE #19: scan: Add versioning to file format
It's not unreasonable to assume that the file format could evolve over time.

Versioning would allow old formats to remain supported, or at the very least fail with an informative error.

The field should be added to a root object that could also include information such as the full path (as mentioned in the bottom of the [scan section](https://github.com/bisgardo/dupe-nukem/tree/031913f045e7ad7d30c3d931c3d6d990f29283f5?tab=readme-ov-file#1-scan) of the readme) or whatever else becomes relevant over time.

### PR DESCRIPTION
**Pull request by bisgardo**
The result `Dir` is wrapped in a new type `Result` with the previous result in key `root` and an integer field `schema_version` for version of the data model. The version starts at 1 to ensure that default decoded value of 0 isn't mistaken for an explicit version.

The root dir name now uses the full path with symlinks completely resolved. The root name of caches must thus match on the absolute, resolved path.

Resolves #19 and #28.

### CODE REVIEW

File: scan/run.go [hunk 1]
```diff
@@ -16,6 +16,13 @@ import (
 // should be skipped when walking a file tree.
 type ShouldSkipPath func(dir, name string) bool
 
+type Result struct {
+	Version int  `json:"version"`
```
Comment (bisgardo) [inline scan/run.go:20]: Consider changing name as explained in #32.

Comment (bisgardo) [reply scan/run.go:20]: I think it should be "schema version".

Comment (bisgardo) [reply scan/run.go]: Or "model version"...
